---

sites:
  bhp:
    name: The British History Podcast
    url: https://www.thebritishhistorypodcast.com/feed/members
    creds:
      user: my-user
      pass: hunter2

log_level: warn
cache_ttl_secs: 30
